import propEnums from "./prop-enums.json";

/**
 * What this package knows about a component beyond how to construct it.
 *
 * The registry answers "what does this name render?". Everything else — which
 * of its props are bounded to a fixed set, which take a value JSON cannot
 * express, whether its `children` is a function it calls or source text it
 * parses — was held in frozen module-level tables that only described
 * `@batthewz/response-ui-react-components`. A component registered through
 * `extendRegistry` therefore rendered but was invisible to every check, and
 * absent from any reference generated for a model.
 *
 * One record per **addressable name**, the same spelling the registry and a
 * document use: `"Card"`, `"Table.Row"`. Merged with `extendContracts`, passed
 * to `ViewRenderer`, `validateViewSpec` and `renderComponentReference` — so a
 * component declared once is rendered, validated and documented from that one
 * declaration.
 */

/** Props the library types with something JSON cannot express. */
export type PropCoercion = "isoDate" | "isoDateRange" | "keyAccessor" | "columnDefs";

/** One row of a component's Props column in the reference. */
export type PropDoc = {
  key: string;
  optional: boolean;
  /** The declared type, collapsed to one line and alias-resolved. */
  type: string;
};

/**
 * Every field is `readonly` because `extendContracts` shares records by
 * reference: a name the caller does not mention is carried over as the same
 * object, so `contractFor(merged, "Card").note = "x"` would reach into the
 * process-global `defaultContracts` and every renderer that never opted in.
 * Copying on merge would cost a deep clone per call and still not stop the
 * base being edited directly; making the mutation a type error does.
 */
export type ComponentContract = {
  /** Section of the reference this component belongs in. */
  readonly category?: string;
  /** The one thing an author would otherwise get wrong. */
  readonly note?: string;

  /**
   * Props bounded to a fixed set of strings, by prop name.
   *
   * The component looks the value up in a table of classes, so a miss renders
   * that dimension absent with nothing in the DOM to notice. JSON has no
   * compiler to catch it, so the validator does.
   */
  readonly propEnums?: Readonly<Record<string, readonly string[]>>;

  /** Props whose document-supplied value needs translating, by prop name. */
  readonly coercions?: Readonly<Record<string, PropCoercion>>;

  /**
   * `children` is a function the component calls with its own state. `args` IS
   * the wire contract: the names a document may `$ref` or `$each` inside those
   * children. `note` says how often the root calls it, which no type carries.
   */
  readonly functionChildren?: { readonly args: readonly string[]; readonly note: string };

  /** `children` is source text the component parses. The value describes how children combine. */
  readonly textChildren?: string;

  /**
   * The renderer owns this component's open state, so `openDialog` and
   * `closeDialog` can reach it. For a controlled-only overlay with no
   * uncontrolled fallback: without this a document could render one and never
   * open it.
   */
  readonly dialog?: true;

  /**
   * The component reads or clones its own children, so the renderer must not
   * put a per-child error boundary between them. `"asChild"` only when the
   * node sets `asChild: true`.
   */
  readonly childInspection?: "always" | "asChild";

  /**
   * Icon slots typed as a component rather than a node — invoked as `<Icon />`
   * internally, so handing one an element throws instead of degrading.
   */
  readonly iconComponentProps?: readonly string[];

  /**
   * What this component's `name` prop means. `"dom"` — it reaches a real form
   * element, so `idScope` must namespace it. `"own"` — the component spends
   * `name` on something else and scoping it would corrupt an authored value.
   *
   * Unclassified means `"own"`: the two failure modes are not symmetric, and
   * the semantic-`name` population is open while the DOM one is closed.
   */
  readonly nameProp?: "dom" | "own";

  /** Reference only: the props table. */
  readonly props?: readonly PropDoc[];
  /** Reference only: the `classNames` slot keys. */
  readonly slots?: readonly string[];
};

export type ComponentContracts = Readonly<Record<string, ComponentContract>>;

/**
 * Props the library types as a fixed set of string literals, keyed
 * `"Component.prop"` (or `"Parent.Child.prop"`).
 *
 * Generated by `scripts/gen-viewspec-doc.mjs` from the library's shipped
 * declarations, alongside the reference doc that shows the same sets — so the
 * advice a document is authored against and the check it is validated against
 * are one artifact. A hand-kept copy would be a second source of truth for the
 * one fact JSON cannot express for itself.
 *
 * Kept flat and exported as-is because it is the shape a prompt builder wants.
 * `defaultContracts` folds it in per component for the checks.
 */
export const PROP_ENUMS: Readonly<Record<string, readonly string[]>> = propEnums;

/**
 * Components whose open/closed state the renderer owns.
 *
 * Shared with the renderer rather than duplicated, and gated by a test that
 * asserts every name still resolves in the live registry.
 */
export const DIALOG_COMPONENTS: ReadonlySet<string> = new Set([
  "Dialog",
  "Drawer",
  "CommandPalette",
]);

/**
 * A registry, structurally — enough to read the addressable names out of it and
 * no more.
 *
 * Spelled here rather than imported so the `/spec` entry point stays free of
 * React: a `ComponentRegistry` satisfies this, and so does anything else shaped
 * like one. A validator running on a server should not have to load a component
 * library to know that `"Cadr"` is not a component.
 */
export type RegistryLike = Readonly<
  Record<string, { subComponents?: Readonly<Record<string, unknown>> }>
>;

/**
 * Every name a document may address, from a registry or from a plain list.
 *
 * The list form is what makes this usable across a process boundary: a host can
 * serialise `listComponentNames(registry)` into a validation service that has
 * no React and no component library at all.
 */
export function componentNamesOf(
  source: Iterable<string> | RegistryLike,
): ReadonlySet<string> {
  if (typeof (source as Partial<Iterable<string>>)[Symbol.iterator] === "function") {
    return new Set(source as Iterable<string>);
  }
  const names = new Set<string>();
  for (const [name, entry] of Object.entries(source as RegistryLike)) {
    names.add(name);
    const subs = entry?.subComponents;
    if (subs) for (const sub of Object.keys(subs)) names.add(`${name}.${sub}`);
  }
  return names;
}

/**
 * Optimal string alignment distance — Levenshtein, plus **transposition of two
 * adjacent characters as a single edit**.
 *
 * Exists so an unknown name is *actionable*: "unknown component" alone leaves an
 * author re-reading a 100-name catalogue to find the one they meant. The
 * transposition case is not a refinement — `"Cadr"` for `"Card"` is two
 * substitutions under plain Levenshtein, so the commonest typo of all would be
 * the one shape that got no suggestion.
 */
function editDistance(a: string, b: string, limit: number): number {
  if (Math.abs(a.length - b.length) > limit) return limit + 1;
  let twoAgo: number[] = [];
  let previous = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i += 1) {
    const current = [i];
    for (let j = 1; j <= b.length; j += 1) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      let value = Math.min(current[j - 1] + 1, previous[j] + 1, previous[j - 1] + cost);
      if (i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) {
        value = Math.min(value, twoAgo[j - 2] + 1);
      }
      current[j] = value;
    }
    twoAgo = previous;
    previous = current;
  }
  return previous[b.length];
}

/** How many leading characters two already-lower-cased names share. */
function sharedPrefix(a: string, b: string): number {
  let i = 0;
  while (i < a.length && i < b.length && a[i] === b[i]) i += 1;
  return i;
}

/**
 * The known name a misspelling most likely meant, if one is close enough.
 *
 * Lives here rather than beside its first caller because two exported surfaces
 * now answer "that name is not one of ours": the validator, judging a document,
 * and `scopeContracts`, judging the list a host asked to document. Two
 * implementations would drift into disagreeing about the same typo.
 */
export function closestName(name: string, names: Iterable<string>): string | undefined {
  const limit = name.length <= 4 ? 1 : 2;
  // Compared lower-cased, so a wrong capital costs nothing. A generator that
  // writes `"cadr"` has made one mistake, not two, and charging it for the case
  // pushed the commonest pair of slips past every sane threshold at once.
  const target = name.toLowerCase();

  let best: string | undefined;
  let bestDistance = limit + 1;
  let bestRank = -1;
  const dotted = name.includes(".");
  for (const candidate of names) {
    // Asymmetric on purpose. A root is no fix for a misspelled part — `"Card"`
    // for `"Table.Rw"` sends an author to a component that cannot go where they
    // put it. But a *part* is very often the fix for a dotless name: dropping
    // the dot is the likeliest slip anyone carrying a PascalCase mental model
    // makes, and `"AccordionItem"` is one edit from a real, renderable name.
    if (dotted && !candidate.includes(".")) continue;
    const lower = dotted ? candidate.toLowerCase() : candidate.toLowerCase().replace(/\./g, "");
    const distance = editDistance(target, lower, limit);
    if (distance > limit || distance > bestDistance) continue;
    // A transposition and a substitution both cost 1, so ties are common and
    // the first candidate seen is not the likelier word: `"Tabel"` tied `Label`
    // with `Table` and, in registry order, sent the author to the wrong one.
    // Prefer the longer shared opening, then the closer length.
    const rank = sharedPrefix(target, lower) * 100 - Math.abs(target.length - lower.length);
    if (distance < bestDistance || rank > bestRank) {
      bestDistance = distance;
      bestRank = rank;
      best = candidate;
    }
  }
  return best;
}

/**
 * A value out of a contract's per-prop record, own properties only.
 *
 * A contract is written as an object literal, by this package and by every
 * host, so it carries `Object.prototype`: `coercions["constructor"]` is the
 * `Object` constructor unless the lookup says otherwise. A document names its
 * own props, so it chooses that key. The tables this replaced were a `Map` and
 * an `Object.hasOwn` guard, and the package's whole hardening posture is
 * own-property lookups — the guarantee has to survive the move.
 */
export function ownProp<T>(
  record: Readonly<Record<string, T>> | undefined,
  key: string,
): T | undefined {
  return record !== undefined && Object.hasOwn(record, key) ? record[key] : undefined;
}

const EMPTY_CONTRACT: ComponentContract = Object.freeze({});

/**
 * This component's record, or an empty one.
 *
 * Own-property lookup only: a document naming `"toString"` or `"constructor"`
 * as a component must not reach an inherited member, the same rule the registry
 * lookup follows.
 */
export function contractFor(
  contracts: ComponentContracts,
  component: string,
): ComponentContract {
  return Object.hasOwn(contracts, component) ? contracts[component] : EMPTY_CONTRACT;
}

/**
 * Adds or replaces contract entries without mutating `base`.
 *
 * Merged **per field**, so naming a component that already has a record adds to
 * it rather than erasing it — a host can attach a note to `Card` without
 * knowing what else `Card`'s record holds. A field present in `extra` replaces
 * the base's field whole; there is no merging *inside* a field, because a
 * partial `propEnums` would be indistinguishable from a complete one.
 */
export function extendContracts(
  base: ComponentContracts,
  extra: ComponentContracts,
): ComponentContracts {
  const next: Record<string, ComponentContract> = Object.create(null) as Record<
    string,
    ComponentContract
  >;
  for (const [name, contract] of Object.entries(base)) next[name] = contract;
  for (const [name, contract] of Object.entries(extra)) {
    next[name] = Object.hasOwn(next, name) ? { ...next[name], ...contract } : contract;
  }
  return next;
}
