import { IDENTITY_CHECKED_PARENTS } from "../registry/child-introspection";
import { takesTextChildren } from "../registry/text-children";
import propEnums from "./prop-enums.json";
import {
  type DataBinding,
  EVENT_ACTION_NAMES,
  type EventAction,
  type EventHandlerSpec,
  type FormDef,
  type ViewNode,
  type ViewSpec,
} from "./types";

/**
 * Dependency-free validation.
 *
 * `@batthewz/response-ui-react-components` states that consumers bring their own
 * validator and the library must not depend on one. This package honours that:
 * zero runtime dependencies, so a Zod/Valibot/ArkType consumer never ends up
 * with a second validator in their bundle.
 */

/**
 * `"error"` — the document does not conform to the format. `ok` is false.
 * `"warning"` — it conforms, but names something the renderer will refuse at
 * render time: a forbidden prop, a script-bearing URL, an unknown action inside
 * a prop, a theme override that is not a custom property, nesting past the
 * depth cap. The document still renders; the offending piece is dropped.
 *
 * The split exists so `ok` means exactly one thing — conformance — and can be
 * mirrored precisely by the optional Zod schema, which is single-tier.
 */
export type IssueSeverity = "error" | "warning";

export type ValidationIssue = {
  path: string;
  message: string;
  severity: IssueSeverity;
};

export type ValidationResult =
  | { ok: true; spec: ViewSpec; issues: ValidationIssue[] }
  | { ok: false; issues: ValidationIssue[] };

/** Issues that make a document non-conforming. */
export const errorsOf = (issues: readonly ValidationIssue[]): ValidationIssue[] =>
  issues.filter((issue) => issue.severity === "error");

/** Issues the renderer acts on without refusing the document. */
export const warningsOf = (issues: readonly ValidationIssue[]): ValidationIssue[] =>
  issues.filter((issue) => issue.severity === "warning");

/**
 * Bounds recursion so a hostile or runaway document cannot exhaust the stack.
 * Matches the render-time guard in NodeRenderer, which renders a diagnostic at
 * the cap rather than refusing — hence a warning, not an error.
 */
export const MAX_NODE_DEPTH = 50;

/** Every action the renderer dispatches. Shared so nothing re-lists them. */
export const EVENT_ACTIONS: ReadonlySet<string> = new Set<EventAction>(EVENT_ACTION_NAMES);

const BINDING_TYPES: ReadonlySet<string> = new Set(["static", "api", "source"]);

/**
 * Props the library types as a fixed set of string literals, keyed
 * `"Component.prop"` (or `"Parent.Child.prop"`).
 *
 * Generated by `scripts/gen-viewspec-doc.mjs` from the library's shipped
 * declarations, alongside the reference doc that shows the same sets — so the
 * advice a document is authored against and the check it is validated against
 * are one artifact. A hand-kept copy would be a second source of truth for the
 * one fact JSON cannot express for itself.
 */
export const PROP_ENUMS: Readonly<Record<string, readonly string[]>> = propEnums;

/** The values this prop accepts, if the library bounds it to a fixed set. */
export function enumeratedValues(component: string, prop: string): readonly string[] | undefined {
  const key = `${component}.${prop}`;
  return Object.hasOwn(PROP_ENUMS, key) ? PROP_ENUMS[key] : undefined;
}

/**
 * Components whose open/closed state the renderer owns so `openDialog` and
 * `closeDialog` can reach them. Each is a controlled-only `<dialog>` with no
 * uncontrolled fallback, so without this a document could render one and never
 * open it.
 *
 * Shared with the renderer rather than duplicated, and gated by a test that
 * asserts every name still resolves in the live registry.
 */
export const DIALOG_COMPONENTS: ReadonlySet<string> = new Set([
  "Dialog",
  "Drawer",
  "CommandPalette",
]);

/** Keys that must never reach `createElement`, whatever the document says. */
export const FORBIDDEN_PROPS: ReadonlySet<string> = new Set([
  "dangerouslySetInnerHTML",
  "ref",
  "key",
  "__proto__",
  "constructor",
  "prototype",
]);

/** Props whose value is a URL, and so can smuggle script execution. */
const URL_PROPS: ReadonlySet<string> = new Set([
  "href",
  "src",
  "action",
  "formAction",
  "poster",
  "data",
  "srcSet",
  "background",
]);

const DANGEROUS_SCHEME = /^(?:javascript|vbscript|data:text\/html)/i;

/**
 * True for characters a browser ignores while parsing a URL scheme: C0/C1
 * controls, spaces, and zero-width marks. `java\tscript:` and `java\nscript:`
 * both navigate, so these are stripped before the scheme is compared — testing
 * the raw string alone is trivially bypassed.
 *
 * Expressed as code-point ranges rather than a regex character class, because a
 * regex containing control characters is itself a lint error, escaped or not.
 */
function isIgnoredInScheme(code: number): boolean {
  return (
    code <= 0x20 ||
    (code >= 0x7f && code <= 0xa0) ||
    (code >= 0x200b && code <= 0x200d) ||
    code === 0xfeff
  );
}

function stripSchemeNoise(value: string): string {
  let out = "";
  for (const char of value) {
    if (!isIgnoredInScheme(char.codePointAt(0) ?? 0)) out += char;
  }
  return out;
}

/** True when a URL string would execute script if the browser followed it. */
export function isDangerousUrl(value: unknown): boolean {
  if (typeof value !== "string") return false;
  return DANGEROUS_SCHEME.test(stripSchemeNoise(value));
}

export function isUrlProp(key: string): boolean {
  return URL_PROPS.has(key);
}

const isPlainObject = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

type Collector = {
  error: (path: string, message: string) => void;
  warn: (path: string, message: string) => void;
};

function checkEventHandler(value: unknown, path: string, at: Collector, severity: IssueSeverity): void {
  const report = severity === "error" ? at.error : at.warn;

  if (!isPlainObject(value)) {
    report(path, "event handler must be an object");
    return;
  }
  const action = value.action;
  if (typeof action !== "string") {
    report(`${path}.action`, "action must be a string");
    return;
  }
  if (!EVENT_ACTIONS.has(action)) {
    report(
      `${path}.action`,
      `unknown action "${action}" (expected one of: ${[...EVENT_ACTIONS].join(", ")})`,
    );
  }
  if (value.payload !== undefined && !isPlainObject(value.payload)) {
    report(`${path}.payload`, "payload must be an object");
  }
}

/**
 * Checks that depend on the component rather than on any prop being present —
 * so they still fire on a node that declares no props at all. Takes the node's
 * own path: what it reports is a fact about the node, and only some of those
 * facts are addressable at a prop.
 */
function checkComponentContract(
  component: string,
  props: Record<string, unknown>,
  children: readonly unknown[],
  path: string,
  at: Collector,
): void {
  // A radio's `value` is the option's identity, so it cannot also carry the
  // binding — the two spellings collide on one key. The bare form is the only
  // one that can express both.
  if (component === "Radio" && isPlainObject(props.value) && "$field" in props.value) {
    at.warn(
      `${path}.props.value`,
      'Radio needs its own "value"; bind it with the bare form — props: { "value": "…", "$field": "form.field" }',
    );
  }

  if (DIALOG_COMPONENTS.has(component) && typeof props.id !== "string") {
    at.warn(
      `${path}.props.id`,
      `${component} needs a literal string "id" for openDialog/closeDialog to target it; without one nothing can open it`,
    );
  }

  // A prop the library types as a fixed set of strings is read by looking the
  // value up in a table of classes. A miss returns nothing, so the component
  // renders with that dimension simply absent — no error, no fallback, and
  // nothing in the DOM to notice. JSON has no compiler to catch it, so this is.
  for (const [key, value] of Object.entries(props)) {
    if (typeof value !== "string") continue;
    const allowed = enumeratedValues(component, key);
    if (allowed && !allowed.includes(value)) {
      at.warn(
        `${path}.props.${key}`,
        `"${value}" is not one of ${component}.${key}'s values (${allowed.join(", ")}); the component will render as if it were unset`,
      );
    }
  }

  // This root parses its children as source text, so a composed child has
  // nothing to contribute and is dropped — and a document that has none at all,
  // by either spelling, hands the parser nothing to parse.
  if (takesTextChildren(component)) {
    const composed = children.map(childComponent).filter((name) => name !== undefined);
    if (composed.length > 0) {
      at.warn(
        `${path}.children`,
        `${component} parses its children as text; ${composed.join(", ")} contributes none and will be dropped — put the source in a string, or in props.children`,
      );
    } else if (children.length === 0 && props.children === undefined) {
      at.warn(
        `${path}.children`,
        `${component} needs its source text, as children or as props.children; without it there is nothing to parse`,
      );
    }
  }

  // These decide something by comparing a child's element type, which can never
  // match through the renderer — the child's type is always the renderer's own
  // node component. The feature is not broken, it just has to be stated rather
  // than inferred, so say so instead of leaving it silently absent.
  const hint = IDENTITY_CHECKED_PARENTS[component];
  if (hint !== undefined && identityCheckWillFail(component, props, children)) {
    at.warn(path, `${component}: ${hint}`);
  }
}

const childComponent = (child: unknown): string | undefined =>
  isPlainObject(child) && typeof child.component === "string" ? child.component : undefined;

const childProps = (child: unknown): Record<string, unknown> =>
  isPlainObject(child) && isPlainObject(child.props) ? child.props : {};

/**
 * Only warns when the document is actually relying on the inference — a `Table`
 * with no `striped` never needed the row numbering, and a warning it cannot act
 * on teaches an author to ignore warnings.
 */
function identityCheckWillFail(
  component: string,
  props: Record<string, unknown>,
  children: readonly unknown[],
): boolean {
  const named = (name: string) => children.some((child) => childComponent(child) === name);
  const missingProp = (name: string, prop: string) =>
    children.some((child) => childComponent(child) === name && childProps(child)[prop] === undefined);

  switch (component) {
    case "Hero":
      return props.overlay === undefined && named("Hero.Background");
    case "AvatarGroup":
      return props.size !== undefined && missingProp("Avatar", "size");
    case "Table.Body":
      return missingProp("Table.Row", "index");
    case "Breadcrumbs":
      return named("Breadcrumbs.Divider");
    case "Combobox.Content":
      return missingProp("Combobox.Item", "index");
    default:
      return false;
  }
}

/**
 * Props are validated as policy, not structure: the Zod mirror types `props` as
 * an open record, so flagging these as errors would make the two validators
 * disagree about conformance. The renderer drops each offending prop.
 */
function checkProps(props: Record<string, unknown>, path: string, at: Collector): void {
  for (const [key, value] of Object.entries(props)) {
    if (FORBIDDEN_PROPS.has(key)) {
      at.warn(`${path}.${key}`, `prop "${key}" is not allowed and will be dropped`);
    }
    if (isUrlProp(key) && isDangerousUrl(value)) {
      at.warn(`${path}.${key}`, "URL scheme is not allowed and will be dropped");
    }
    if (isPlainObject(value) && "action" in value) {
      checkEventHandler(value, `${path}.${key}`, at, "warning");
    }
  }
}

function checkNode(node: unknown, path: string, depth: number, at: Collector): void {
  if (depth > MAX_NODE_DEPTH) {
    at.warn(path, `node nesting exceeds ${MAX_NODE_DEPTH} levels and will not render past it`);
    return;
  }
  if (typeof node === "string") return;
  if (!isPlainObject(node)) {
    at.error(path, "node must be a string or an object");
    return;
  }

  if ("$ref" in node) {
    if (typeof node.$ref !== "string") at.error(`${path}.$ref`, "$ref must be a string");
    return;
  }

  if ("$each" in node) {
    if (typeof node.$each !== "string") at.error(`${path}.$each`, "$each must be a string");
    if (typeof node.as !== "string" || node.as.length === 0) {
      at.error(`${path}.as`, "as must be a non-empty string");
    }
    if (node.node === undefined) at.error(`${path}.node`, "node is required");
    else checkNode(node.node, `${path}.node`, depth + 1, at);
    return;
  }

  if ("$cond" in node) {
    if (typeof node.$cond !== "string") at.error(`${path}.$cond`, "$cond must be a string");
    if (node.then === undefined) at.error(`${path}.then`, "then is required");
    else checkNode(node.then, `${path}.then`, depth + 1, at);
    if (node.else !== undefined) checkNode(node.else, `${path}.else`, depth + 1, at);
    return;
  }

  if ("component" in node) {
    if (typeof node.component !== "string" || node.component.length === 0) {
      at.error(`${path}.component`, "component must be a non-empty string");
    }
    const props = isPlainObject(node.props) ? node.props : undefined;
    if (node.props !== undefined && props === undefined) {
      at.error(`${path}.props`, "props must be an object");
    } else if (props) {
      checkProps(props, `${path}.props`, at);
    }
    if (typeof node.component === "string") {
      const children = Array.isArray(node.children) ? node.children : [];
      checkComponentContract(node.component, props ?? {}, children, path, at);
    }
    if (node.children !== undefined) {
      if (!Array.isArray(node.children)) at.error(`${path}.children`, "children must be an array");
      else {
        node.children.forEach((child, i) =>
          checkNode(child, `${path}.children[${i}]`, depth + 1, at),
        );
      }
    }
    return;
  }

  at.error(path, 'node must have one of: "component", "$ref", "$each", "$cond"');
}

function checkBinding(value: unknown, path: string, at: Collector): void {
  if (!isPlainObject(value)) {
    at.error(path, "data binding must be an object");
    return;
  }
  const type = value.type;
  if (typeof type !== "string" || !BINDING_TYPES.has(type)) {
    at.error(`${path}.type`, `binding type must be one of: ${[...BINDING_TYPES].join(", ")}`);
    return;
  }
  if (type === "static" && !("value" in value)) {
    at.error(`${path}.value`, "static binding requires value");
  }
  if (type === "api") {
    if (typeof value.endpoint !== "string") {
      at.error(`${path}.endpoint`, "api binding requires endpoint");
    }
    if (value.method !== undefined && typeof value.method !== "string") {
      at.error(`${path}.method`, "method must be a string");
    }
    if (value.headers !== undefined) {
      if (!isPlainObject(value.headers)) {
        at.error(`${path}.headers`, "headers must be an object");
      } else {
        for (const [name, header] of Object.entries(value.headers)) {
          if (typeof header !== "string") {
            at.error(`${path}.headers.${name}`, "header must be a string");
          }
        }
      }
    }
  }
  if (type === "source") {
    if (typeof value.source !== "string") {
      at.error(`${path}.source`, "source binding requires source");
    }
    if (value.params !== undefined && !isPlainObject(value.params)) {
      at.error(`${path}.params`, "params must be an object");
    }
  }
}

function checkForm(value: unknown, path: string, at: Collector): void {
  if (!isPlainObject(value)) {
    at.error(path, "form must be an object");
    return;
  }
  if (!isPlainObject(value.fields)) {
    at.error(`${path}.fields`, "fields must be an object");
  } else {
    for (const [name, field] of Object.entries(value.fields)) {
      if (!isPlainObject(field)) {
        at.error(`${path}.fields.${name}`, "field must be an object");
        continue;
      }
      if (!("initialValue" in field)) {
        at.error(`${path}.fields.${name}.initialValue`, "initialValue is required");
      }
      if (field.validation !== undefined && !isPlainObject(field.validation)) {
        at.error(`${path}.fields.${name}.validation`, "validation must be an object");
      }
    }
  }
  // Declared handlers are structural: the Zod mirror types them with an enum.
  if (value.onSubmit !== undefined) {
    checkEventHandler(value.onSubmit, `${path}.onSubmit`, at, "error");
  }
}

/**
 * Validates an untrusted document.
 *
 * `ok: false` means the document does not conform and should be rejected.
 * `ok: true` with warnings means it renders, minus whatever each warning names.
 * The renderer itself never consults this — it degrades per node — so validation
 * is a gate you choose to put in front of it.
 */
export function validateViewSpec(input: unknown): ValidationResult {
  const issues: ValidationIssue[] = [];
  const at: Collector = {
    error: (path, message) => issues.push({ path, message, severity: "error" }),
    warn: (path, message) => issues.push({ path, message, severity: "warning" }),
  };

  if (!isPlainObject(input)) {
    return {
      ok: false,
      issues: [{ path: "", message: "spec must be an object", severity: "error" }],
    };
  }

  if (input.version !== 1) at.error("version", "version must be the number 1");
  if (typeof input.title !== "string" || input.title.length === 0) {
    at.error("title", "title must be a non-empty string");
  } else if (input.title.length > 200) {
    at.error("title", "title must be at most 200 characters");
  }
  if (input.description !== undefined && typeof input.description !== "string") {
    at.error("description", "description must be a string");
  }
  if (input.theme !== undefined && typeof input.theme !== "string") {
    at.error("theme", "theme must be a string");
  }

  if (input.themeOverrides !== undefined) {
    if (!isPlainObject(input.themeOverrides)) {
      at.error("themeOverrides", "themeOverrides must be an object");
    } else {
      for (const [key, value] of Object.entries(input.themeOverrides)) {
        if (typeof value !== "string") {
          at.error(`themeOverrides.${key}`, "value must be a string");
        } else if (!key.startsWith("--")) {
          at.warn(
            `themeOverrides.${key}`,
            "key must be a CSS custom property starting with '--'; it will be ignored",
          );
        }
      }
    }
  }

  if (input.data !== undefined) {
    if (!isPlainObject(input.data)) at.error("data", "data must be an object");
    else {
      for (const [key, binding] of Object.entries(input.data)) {
        checkBinding(binding, `data.${key}`, at);
      }
    }
  }

  if (input.forms !== undefined) {
    if (!isPlainObject(input.forms)) at.error("forms", "forms must be an object");
    else {
      for (const [key, form] of Object.entries(input.forms)) {
        checkForm(form, `forms.${key}`, at);
      }
    }
  }

  if (input.state !== undefined && !isPlainObject(input.state)) {
    at.error("state", "state must be an object");
  }

  if (input.root === undefined) at.error("root", "root is required");
  else checkNode(input.root, "root", 0, at);

  const ok = errorsOf(issues).length === 0;
  return ok ? { ok: true, spec: input as unknown as ViewSpec, issues } : { ok: false, issues };
}

/** Narrowing helper for consumers that only need a yes/no. */
export function isViewSpec(input: unknown): input is ViewSpec {
  return validateViewSpec(input).ok;
}

export type { DataBinding, EventHandlerSpec, FormDef, ViewNode, ViewSpec };
